version: "3.7"

services:
  jenkins:
    # image: jenkins/jenkins:lts
    build: .
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8181:8080"
      - "50000:50000"

volumes:
  jenkins_home: